// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SistemaPaisa.Infrastructure.Persistence;

#nullable disable

namespace SistemaPaisa.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520210000_AddModuleNavigationFields")]
    partial class AddModuleNavigationFields
    {
    }
}
